# Generated by Django 4.0.4 on 2022-05-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
