# Generated by Django 4.0.4 on 2022-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_msg', models.TextField()),
                ('msg_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
